general:
  debug: false
  instance_name: "SearXNG-API"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  open_metrics: ''

brand:
  docs_url: https://docs.searxng.org/
  issue_url: https://github.com/searxng/searxng/issues

search:
  safe_search: 0
  autocomplete: ""
  favicon_resolver: ""
  default_lang: "auto"
  max_page: 0

  ban_time_on_fail: 5
  max_ban_time_on_fail: 30

  suspended_times:
    SearxEngineAccessDenied: 5
    SearxEngineCaptcha: 10
    SearxEngineTooManyRequests: 5
    cf_SearxEngineCaptcha: 20
    cf_SearxEngineAccessDenied: 5
    recaptcha_SearxEngineCaptcha: 20

  formats:
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false
  limiter: false
  public_instance: false

  secret_key: ${SEARXNG_SECRET_KEY}

  image_proxy: false
  http_protocol_version: "1.1"
  method: GET

  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

valkey:
  url: false

ui:
  enabled: false
  static_path: ""
  templates_path: ""
  query_in_title: false
  default_locale: "en"
  url_formatting: full

outgoing:
  request_timeout: 10.0
  max_request_timeout: 40.0
  useragent_suffix: ""

  pool_connections: 100
  pool_maxsize: 10
  enable_http2: true

  proxies:
    all://:
      - socks5h://haproxy:9050

  using_tor_proxy: true

plugins:
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.calculator.SXNGPlugin:
    active: false
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: false
  searx.plugins.hash_plugin.SXNGPlugin:
    active: false
  searx.plugins.self_info.SXNGPlugin:
    active: false
  searx.plugins.unit_converter.SXNGPlugin:
    active: false
  searx.plugins.time_zone.SXNGPlugin:
    active: false
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: false
  searx.plugins.tor_check.SXNGPlugin:
    active: false

hostnames:
  remove:
    - '(.*\.)?facebook\.com$'
    - '(.*\.)?instagram\.com$'
    - '(.*\.)?twitter\.com$'
    - '(.*\.)?x\.com$'
    - '(.*\.)?tiktok\.com$'
    - '(.*\.)?pinterest\.com$'
  high_priority:
    - '(.*\.)?wikipedia\.org$'
    - '(.*\.)?arxiv\.org$'
    - '(.*\.)?github\.com$'
  replace:
    '(.*\.)?wikipedia\.org$': 'en.m.wikipedia.org'

checker:
  off_when_debug: true

engines:
  - name: brave
    engine: brave
    shortcut: br
    categories: general
    timeout: 8.0

  - name: qwant
    engine: qwant
    shortcut: qw
    categories: general
    timeout: 8.0

  - name: mojeek
    engine: mojeek
    shortcut: mj
    categories: general
    timeout: 8.0

  - name: google
    engine: google
    shortcut: g
    categories: general
    timeout: 8.0
    use_mobile_ui: true

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox", "list"]
    categories: general

  - name: wikidata
    engine: wikidata
    shortcut: wd
    display_type: ["infobox"]
    categories: general

  - name: stackoverflow
    engine: stackexchange
    shortcut: st
    api_site: 'stackoverflow'
    categories: it
    timeout: 8.0

  - name: github
    engine: github
    shortcut: gh
    categories: it

  - name: geeksforgeeks
    engine: xpath
    paging: true
    search_url: https://www.geeksforgeeks.org/search/?gq={query}&page={pageno}
    results_xpath: //article
    url_xpath: .//a[1]/@href
    title_xpath: .//h2|.//h3
    content_xpath: .//p
    shortcut: gfg
    categories: it
    timeout: 8.0

  - name: mdn
    shortcut: mdn
    engine: json_engine
    categories: it
    paging: true
    search_url: https://developer.mozilla.org/api/v1/search?q={query}&page={pageno}
    results_query: documents
    url_query: mdn_url
    url_prefix: https://developer.mozilla.org
    title_query: title
    content_query: summary
    timeout: 8.0

  - name: pypi
    engine: pypi
    shortcut: pypi
    categories: it

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    categories: it

  - name: arch linux wiki
    engine: archlinux
    shortcut: al
    categories: it

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'
